### ISSUE TITLE
Current Master Branch Bugs

### ISSUE THREAD

**Issue by cpritcha** [comses/miracle#80]
- Delete project doesn't delete a project (a projects datasets or archive do not get deleted when the delete button is pressed) (Master branch only)
- Upload archive errors on project upload (Master branch only)
- Run script does nothing when pressed (Master branch only)
- Serializer error when a project is created (get a 'ValueError at /dashboard/
The 'submitted_archive' attribute has no file associated with it.'). If I add the project in the elm branch and then checkout the master branch I do not get an error (Master branch only)
- Radiant not displaying in iframe (will display in a new window though) (Master Branch only)

**Comment by alee** [comment]
Looks like I may have forgotten to commit all of my changes on my dev box before I left as I'm not experiencing those issues on borges. I'm actually not able to login to my box right now because of some weirdness with /etc/hosts.allow and the asu VPN - let me know when you power on your machine again and I'll try to tunnel through it.

**Comment by alee** [comment]
Hmm, this appears to all related to the submitted_archive serializer issue #81. Not able to replicate any of the other problems you experienced. Please test again and close if spurious.

**Comment by cpritcha** [comment]
I've gone through all the issues and everything works now. Closing.
